# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: true
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip

env:
  - KERAS_IMPLEMENTATION="tensorflow"

before_script:
  - pip2.7 install --upgrade --ignore-installed --user travis pip setuptools wheel virtualenv
  - pip2.7 install --upgrade --ignore-installed --user travis keras h5py pyyaml requests Pillow scipy theano
  - R -e 'tensorflow::install_tensorflow()'

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
